version: '3.9'

services:
    postgres:
      image: postgres
      container_name: postgresql
      restart: on-failure
      environment: 
        - POSTGRES_DB=${USER_DB_NAME}
        - POSTGRES_USER=${USER_DB_USER}
        - POSTGRES_PASSWORD=${USER_DB_PASSWORD}
      networks: 
        - main
      ports: 
        - "5432:5432"
      volumes:
        - ./data/postgres:/var/lib/postgresql/data 

    pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin
      restart: on-failure
      environment:
        - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
        - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      ports:
        - "5050:80"
      volumes:
        - ./data/pgadmin:/var/lib/pgadmin/data
      networks:
        - main

        
    user_services:
      container_name: user_services
      build: .
      command: sh -c "
                  python manage.py makemigrations &&
                  python manage.py migrate && 
                  python manage.py collectstatic --no-input && 
                  gunicorn -k gevent config.wsgi:application -b 0.0.0.0:8001"
      restart: on-failure
      expose:
        - "8001"
      depends_on:
        - postgres
      networks:
        - main
      volumes: 
        - .:/user_services/
        - ./static:/user_services/static

    
    nginx:
      container_name: nginx
      command: nginx -g 'daemon off;'
      image: nginx
      restart: on-failure
      depends_on:
        - user_services
      networks: 
        - main
      ports: 
        - "80:80"
      volumes: 
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./static:/user_services/static


networks: 
    main:
        external: true

volumes: 
     
    static_user:
        external: true
     
    data:
        external: true
